---
- name: install-required-ubuntu-packages
  apt:
    name: "{{ item }}"
    # latest is allowed, because packages with specific version
    # like elasticsearch will be marked to its specified version
    state: latest
    update_cache: yes
    install_recommends: yes
  with_items:
    - curl
    - wget
    - unzip
    - whois
    - rsync
    - htop
    - apt-transport-https
    - apt-show-versions    

- name: download-wildfly  
  get_url:
    url: http://download.jboss.org/wildfly/10.0.0.Final/wildfly-10.0.0.Final.tar.gz
    dest: /opt/wildfly-10.0.0.Final.tar.gz
    timeout: 300 # 5 minutes
  register: get_url_err

- name: extract-wildfly-archive
  unarchive:
    src: /opt/wildfly-10.0.0.Final.tar.gz
    dest: /opt/
    remote_src: yes
  register: extracted-wildfly

- name: link-to-wildfly-directory
  file: src=/opt/wildfly-10.0.0.Final dest=/opt/wildfly state=link

- debug: var=get_url_err

- name: copy-config-file
  template: src=standalone-default.xml.j2 dest=/opt/wildfly/standalone/configuration/standalone.xml
  notify: restart-wildfly

- name: add-group-wildfly"
  group: name={{ wf_group }}
  
- name: add-user-wildfly
  user: name={{ wf_user }} group={{ wf_group }} home={{ wf_home }}

- name: change-permission-wildfly-installation
  file: path=/opt/wildfly-10.0.0.Final owner={{ wf_user }} group={{ wf_group }} state=directory recurse=yes

- name: create-etc-wildfly
  file:
    path: /etc/wildfly
    state: directory
    mode: 0755

- name: copy-config-file-etc
  copy: src=wildfly.conf dest=/etc/wildfly/wildfly.conf mode=0755

- name: copy-the-init-script
  copy: src=wildfly.service dest=/etc/systemd/system/wildfly.service mode=0755

- name: enable-wildFly-to-be-started-at-boot
  systemd: name=wildfly enabled=yes state=started